---
- name: install artifactory
  hosts: artifactory
  vars_files:
    - vars/secret-vars.yml
    - vars/postgres-vars.yaml

  roles:
    - jfrog.platform.postgres
  tasks:
    - name: download and install artifactory
      shell: "{{ item }}"
      loop:
        - 'wget https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo -O jfrog-artifactory-rpms.repo'
        - 'mv jfrog-artifactory-rpms.repo /etc/yum.repos.d/'
        - 'yum update -y && sudo yum install -y jfrog-artifactory-oss'  
